#version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      # to run our script in docker/mysql/init.sql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

      # space after '-' is required, otherwise it might throw error